### ISSUE TITLE
I need help installing it

### ISSUE THREAD

**Issue by cmd-k** [methodpark/meeting-room-display#2]
Hello,
i tried deploying the mrd to one of my RasPi's. I think i got the installation routine wrong. Why do i have to establish passwordless ssh access on GitLab. I dont want to use Gitlab i just want to install the mrd locally on the Pi. I also tried running the make file in the repo's root but it didn't went well. What is meant by the "tags" refferenced under "continous integration" in the readme.md file? Where should i append these tags (installation, deployment, hotspot...). Iam very sorry if it is inappropriate asking here. Iam just starting to understand kivy and python and thought it would be nice starting with integrating something usefull. It would be awesome if someone could refer me to a source where i may find some answers.
Thanks :)

**Comment by lusiux** [comment]
The passwordless ssh access is only necessary for continuous deployment.

As you only want to try kivy and python, please look at the section "Setting up the project for development on Linux (Ubuntu)" in the Readme.md.
