### ISSUE TITLE
Connection to EWS instead of O365

### ISSUE THREAD

**Issue by JohnnyFlash1887** [methodpark/meeting-room-display#4]
Hello,
I´m pretty new to github and projects like this. 
At the moment I try to find a solution regarding meeting room displays, which led me to your project. My question is, is there any possibility to connect to Exchange on Premise via EWS instead of O365? I mean, instead of using your mentioned Python O365 library, could I use something like exchangelib for Python and it should work?
I´m not that into programming/coding/scripting, so I wonder if the interfaces fit to each other.
 
I´m doing my final graduation project where I wanted to implement such signages for our meeting rooms, and my environment only has an Exchange 2016 on premise as source-server. 

Or is there any other workaround?

Regards, and thanks for your answer!

**Comment by ohaz** [comment]
Sorry for the late answer. Corona.

The "backend" is added in a modular way. You'd have to script an Exchange backend yourself, but you'd basically have to write a module similar to mrd/outlook.py. You'd additionally have to change https://github.com/methodpark/meeting-room-display/blob/master/mrd/display_main.py#L120 to use your new backend. If you need any help with this, please let us know :)

**Comment by JohnnyFlash1887** [comment]
No problem, and thanks for your answer.
I hope nothing too serious with that sh*t virus?
I already found another solution for my problem, but thanks anyway :) Should have updated my post, I guess. sorry for my unreliability. But, thanks again, and stay safe! :)
